-- MySQL Script generated by MySQL Workbench
-- Fri 16 Feb 2024 08:31:08 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chusadb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chusadb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chusadb2` ;
USE `chusadb2` ;

-- -----------------------------------------------------
-- Table `chusadb2`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chusadb2`.`Accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `currency` DECIMAL(5,2) ZEROFILL NOT NULL,
  `creationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chusadb2`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chusadb2`.`Transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(5,2) NULL,
  `from_Account_id` INT NOT NULL,
  `to_Account_id` INT NOT NULL,
  `creationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Transactions_Accounts_idx` (`from_Account_id` ASC) VISIBLE,
  INDEX `fk_Transactions_Accounts1_idx` (`to_Account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions_Accounts`
    FOREIGN KEY (`from_Account_id`)
    REFERENCES `chusadb2`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Accounts1`
    FOREIGN KEY (`to_Account_id`)
    REFERENCES `chusadb2`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
