-- MySQL Script generated by MySQL Workbench
-- Sun 18 Feb 2024 09:09:37 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chusadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chusadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chusadb` ;
USE `chusadb` ;

-- -----------------------------------------------------
-- Table `chusadb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chusadb`.`Accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `currency` DECIMAL(10,2) ZEROFILL NOT NULL,
  `creationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chusadb`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chusadb`.`Transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(10,2) NULL,
  `from_Account_id` INT NOT NULL,
  `to_Account_id` INT NOT NULL,
  `creationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Transactions_Accounts_idx` (`from_Account_id` ASC) VISIBLE,
  INDEX `fk_Transactions_Accounts1_idx` (`to_Account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions_Accounts`
    FOREIGN KEY (`from_Account_id`)
    REFERENCES `chusadb`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Accounts1`
    FOREIGN KEY (`to_Account_id`)
    REFERENCES `chusadb`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `chusadb` ;

-- -----------------------------------------------------
-- Placeholder table for view `chusadb`.`Statements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chusadb`.`Statements` (`creationDate` INT, `fromUserName` INT, `fromUserId` INT, `toUserName` INT, `toUserId` INT, `value` INT);

-- -----------------------------------------------------
-- View `chusadb`.`Statements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chusadb`.`Statements`;
USE `chusadb`;
CREATE  OR REPLACE VIEW `Statements` AS 
SELECT t.creationDate, fa.name fromUserName, fa.id fromUserId, ta.name toUserName, ta.id toUserId, t.value value FROM Transactions t
JOIN Accounts fa ON t.from_Account_id = fa.id JOIN Accounts ta ON t.to_Account_id = ta.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
